app/CanBeVoted.php
<?php

namespace App;

use App\Vote;
use Collective\Html\HtmlFacade as Html;

trait CanBeVoted
{

    //!agergamos la relacion, un post va a tener varios votos
    public function votes()
    {
        // !morphMany es porque es una relación polimorfica la idea es que este trait lo use cualquier entidad...
        /** en una relación polimorfica hay que estalecer ademas del modelo
         *  en el segundo parámetro el nombre genérico de los objetos relacionados */
        return $this->morphMany(Vote::class, 'votable');
    }

    // ! definimos una relación y luego la cargamos de forma ambiciosa en el momento de ejecutar la consulta SQL en LisPostController.php en el objeto principal
    // Podemos decir que cada post tiene un voto
    public function userVote()
    {
        // es una relacion polimorfica...
        return $this->morphOne(Vote::class, 'votable')
            //distinguimos el voto de un usuario con una condición
            // !se pueden encadenar condiciones a nuestras relaciones
            ->where('user_id', auth()->id()) //si esto devuelve null no sirve
            /** Entonces con withDefault() de Eloquent siempre vamos a obtener
            * un voto a pesar de que el usuario no haya votado. usamos el framework
            * para que nos devuelva si o si un objeto si no da un error*/
            ->withDefault();
    }
    public function getCurrentVoteAttribute()
    {
        // no tiene sentido esperar un voto de alguien que no esta conectado
        if(auth()->check()) {
            //usamos la relación que sabemos nos va a traer un solo voto
            //! debemos primero comprobar si el usuario voto o no, no puede devolver null
            return $this->userVote->vote; // obtenemos el valor de la columna vote
        }
        // de lo contrario retorna null
    }
    // otra propiedad dinamica
    public function getVoteComponentAttribute()
    {
        //solo si el usuario esta conectado puede votar
        if (auth()->check()) {
            return Html::tag('app-vote', '', [
                // pasamos el nombre del modulo sobre el cual queremos votar...
                'module' => $this->getTable(), // posts or comments
                'id' => $this->id,
                'score' => $this->score,
                'vote' => $this->current_vote
            ]);
        }
    }
    public function getVoteFrom(User $user)//recibimos al usuario como un parametro y no dependemos del usuario actual
    {

        // !usamos la relación que cargamos de forma ambiciosa en ListPostController
        //tenemos que comprobar que usuario voto por el post
        return  $this->votes //con los parentesis armamos una consulta, sin ellos trae todos los votos de la DB
            ->where('user_id', $user->id) //filtro por el usuario, no necesito por post porque ya esta implicito en la relación.
            ->value('vote'); //obtenemos el voto...

            //si la variable no es null
            if ($userVote) {
                return $userVote->vote; //retornamos el voto del usuario...
            } // por defecto devuelve null


        /** revisamos el modelo de votos, donde el voto sea igual al id del usuario
         * conectado, y solo queremos obtener el valor de la columna vote.
         */
        /* tenemos que agregar los condicionales si no no funciona...
        return Vote::query()

            ->where('post_id', $this->id) //y para el post actual
            ->value('vote'); //+1, -1, null */
    }
    public function upvote()
    {
        $this->addVote(1);
    }

    public function downvote()
    {
        $this->addVote(-1);
    }

    protected function addVote($amount)
    {
        // Usamos el modelo de Eloquent
        /** Entonces eloquent completa los dos campor de la relación
         * polimórfica, votable_id, votable_type */
        $this->votes()->updateOrCreate(
            ['user_id' => auth()->id()],
            ['vote' => $amount]
        );

        $this->refreshPostScore();

    }

    public function undoVote()
    {
        $this->votes()
            ->where('user_id', auth()->id())
            ->delete();

        /* Vote::where([
            'post_id' => $this->id,
            'user_id' => auth()->id(),
        ])->delete(); */

        $this->refreshPostScore();
    }

    protected function refreshPostScore()
    {
        $this->score  = $this->votes()->sum('vote');;

        /*  $this->score = Vote::query()
            ->where(['post_id' => $this->id])
            ->sum('vote');
        */
        $this->save();
    }
}

app/Comment.php
<?php

namespace App;

use App\CanBeVoted;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    use CanBeVoted; //!cualquier modelo puede ser votado usando este trait

    protected $fillable = ['comment', 'post_id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function post()
    {
        return $this->belongsTo(Post::class);
    }

    public function markAsAnswer()
    {
        $this->post->pending = false;
        $this->post->answer_id = $this->id;

        $this->post->save();
    }

    public function getAnswerAttribute()
    {
        return $this->id === $this->post->answer_id;
    }
}

app/Post.php
<?php

namespace App;

use App\CanBeVoted;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Model;
use GrahamCampbell\Markdown\Facades\Markdown;

class Post extends Model
{
    use CanBeVoted;

    protected $fillable = ['title', 'content', 'category_id'];

    protected $casts = [
        'pending' => 'boolean',
        'score' => 'integer',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function subscribers()
    {
        return $this->belongsToMany(User::class, 'subscriptions');
    }

    public function latestComments()
    {
        return $this->comments()->orderBy('created_at', 'DESC');
    }

    public function scopeCategory($query, Category $category)
    {
        if ($category->exists) {
           $query->where('category_id', $category->id);
        }
    }

    public function scopePending($query)
    {
        $query->where('pending', true);
    }

    public function scopeCompleted($query)
    {
        $query->where('pending', false);
    }

    public function scopeByUser($query, User $user)
    {
        $query->where('user_id', $user->id);
    }

    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = $value;

        $this->attributes['slug'] = Str::slug($value);
    }

    public function getUrlAttribute()
    {
        return route('posts.show', [$this->id, $this->slug]);
    }

    public function getSafeHtmlContentAttribute()
    {
        return Markdown::convertToHtml(e($this->content));
    }
}

app/User.php
<?php

namespace App;

use App\Notifications\PostCommented;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Notification;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email', 'username', 'first_name', 'last_name',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function subscriptions()
    {
        return $this->belongsToMany(Post::class, 'subscriptions');
    }

    public function createPost(array $data)
    {
        $post = new Post($data);

        $this->posts()->save($post);

        $this->subscribeTo($post);

        return $post;
    }

    public function comment(Post $post, $message)
    {
        $comment = new Comment([
            'comment' => $message,
            'post_id' => $post->id,
        ]);

        $this->comments()->save($comment);

        // Notify subscribers
        Notification::send(
            $post->subscribers()->where('users.id', '!=', $this->id)->get(),
            new PostCommented($comment)
        );

        return $comment;
    }

    public function isSubscribedTo(Post $post)
    {
        return $this->subscriptions()->where('post_id', $post->id)->count() > 0;
    }

    public function subscribeTo(Post $post)
    {
        $this->subscriptions()->attach($post);
    }

    public function unsubscribeFrom(Post $post)
    {
        $this->subscriptions()->detach($post);
    }

    public function owns(Model $model)
    {
        return $this->id === $model->user_id;
    }

    public function getNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Register</div>
                    <div class="panel-body">
                        {!! Form::open(['method' => 'POST', 'route' => 'posts.store']) !!}

                            {!! Field::text('title') !!}

                            {!! Field::textarea('content') !!}

                            {!! Field::select('category_id', $categories) !!}

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Publicar
                                    </button>
                                </div>
                            </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <h1>
                {{ $category->exists ? 'Posts de '.$category->name : 'Posts' }}
            </h1>
        </div>
    </div>
    <div class="row">
        @include('posts.sidebar')
        <div class="col-md-10">
            {!! Form::open(['method' => 'get', 'class' => 'form form-inline']) !!}
                {!! Form::select(
                    'orden',
                    trans('options.posts-order'),
                    request('orden'),
                    ['class' => 'form-control']
                ) !!}
                <button type="submit" class="btn btn-default">Ordenar</button>
            {!! Form::close() !!}

            @each('posts.item', $posts, 'post')

            {{ $posts->render() }}
        </div>
    </div>
@endsection

resources/views/posts/item.blade.php
<article>
    <h4><a href="{{ $post->url }}">{{ $post->title }}</a></h4>

    <p>
        Publicado por <a href="#">{{ $post->user->name }}</a>
        {{ $post->created_at->diffForHumans() }}
        en <a href="{{ $post->category->url }}">{{ $post->category->name }}</a>.
        @if ($post->pending)
            <span class="label label-warning">Pendiente</span>
        @else
            <span class="label label-success">Completado</span>
        @endif

        {{-- !obtenemos con un atributo dinamico el componente de VUE
                desde cualquier lugar de la app --}}
        {!! $post->vote_component !!}

        {{-- pasamos el post del id por la url --}}
        {{-- <app-vote post_id="{{ $post->id }}"
                score="{{ $post->score }}"
                vote="{{ $post->current_vote }}">
        </app-vote> --}}

    <hr>
</article>

resources/views/posts/show.blade.php
@extends('layouts/app')

@section('content')
    <div class="row">
        <div class="col-md-10">
            <h1>{{ $post->title }}</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8">
            <p>
                Publicado por <a href="#">{{ $post->user->name }}</a>
                {{ $post->created_at->diffForHumans() }}
                en <a href="{{ $post->category->url }}">{{ $post->category->name }}</a>.
                @if ($post->pending)
                    <span class="label label-warning">Pendiente</span>
                @else
                    <span class="label label-success">Completado</span>
                @endif
            </p>


            {{-- !obtenemos con un atributo dinamico el componente de VUE
                desde cualquier lugar de la app --}}
            {!! $post->vote_component !!}

            {{--  usamos la propiedad dinamica current_vote definida en el trait
                 CanBeVoted. le pasamos el id del post por la url  --}}
            {{-- <app-vote post_id="{{ $post->id }}"
                      score="{{ $post->score }}"
                      vote="{{ $post->current_vote }}">
            </app-vote> --}}

            {!! $post->safe_html_content !!}

            @if (auth()->check())
                @if (!auth()->user()->isSubscribedTo($post))
                    {!! Form::open(['route' => ['posts.subscribe', $post], 'method' => 'POST']) !!}
                    <button type="submit" class="btn btn-primary">Suscribirse al post</button>
                    {!! Form::close() !!}
                @else
                    {!! Form::open(['route' => ['posts.unsubscribe', $post], 'method' => 'DELETE']) !!}
                    <button type="submit" class="btn btn-default">Desuscribirse del post</button>
                    {!! Form::close() !!}
                @endif
            @endif

            <hr>

            <h4>Comentarios</h4>

            {{-- todo: Paginate comments! --}}

            @foreach($post->latestComments as $comment)
            {{-- le decimos en lavaravel dusk que busque para votar en cualquier
                elemento con la clase comment y lo diferenciamos del elemento para votar por post--}}
                 <article class="comment {{ $comment->answer ? 'answer' : '' }}">
                    {{-- todo: support markdown in the comments as well! --}}

                    {{ $comment->comment }}

                    {{ $comment->vote_component }}

                    @if(Gate::allows('accept', $comment) && !$comment->answer)
                        {!! Form::open(['route' => ['comments.accept', $comment], 'method' => 'POST']) !!}
                        <button type="submit" class="btn btn-default">Aceptar respuesta</button>
                        {!! Form::close() !!}
                    @endif
                </article>

                <hr>
            @endforeach

            {!! Form::open(['route' => ['comments.store', $post], 'method' => 'POST', 'class' => 'form']) !!}

            {!! Field::textarea('comment', ['class' => 'form-control', 'rows' => 6, 'label' => 'Escribe un comentario']) !!}

            <button type="submit" class="btn btn-primary">
                Publicar comentario
            </button>

            {!! Form::close() !!}
        </div>

        @include('posts.sidebar')
    </div>
@endsection

resources/views/posts/sidebar.blade.php
<div class="col-md-2">
    <h4>Filtros</h4>
    {!! Menu::make($filters, 'nav filters') !!}
    <h4>Categorías</h4>
    {!! Menu::make($categoryItems, 'nav categories') !!}
</div>